export shelly_endpoint_uri="some_url"
export shelly_auth_key="abcd"
export shelly_device_id="abcd"
export brevo_url="some url"
export brevo_api_key="some key"
export notification_interval_minutes="6"
export sender_email=test@gmail.com
export recipient_email_addresses='["1234567890@vtext.com"]'
export awake_start_end_hours='[6, 22]'
